services:
  mysql:
    image: mysql:9.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: mitm-packet-sniffer
      MYSQL_PASSWORD: mitm-packet-sniffer-password
      MYSQL_DATABASE: mitm-packet-sniffer
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: mitm-packet-sniffer
      PMA_PASSWORD: mitm-packet-sniffer-password
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - default
